name: Upload YouTube Shorts

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual runs

jobs:
  upload-short:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt

    - name: Run upload script
      env:
        GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
        GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
        GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        ARCHIVE_FOLDER_ID: ${{ secrets.ARCHIVE_FOLDER_ID }}
      run: |
        python scripts/main.py
